### ISSUE TITLE
can no longer get manifest for custom tarball URL

### ISSUE THREAD

**Issue by kenany** [zkat/pacote-old#132] opened 2018-01-17 01:13 UTC
Repro:

```javascript
const pacote = require('./');

pacote.manifest('pacote@https://github.com/zkat/pacote/archive/v7.1.1.tar.gz')
  .then(pkg => {
    console.log(pkg);
  });

```

As of https://github.com/zkat/pacote/commit/149a4b5e0464ac3bf383daab10daa4af84019431 ("feat(resolved): add opts.resolved for cache stuff"), this code now throws:

```
Unhandled rejection Error: Only tag, version, and range are supported
    at pickManifest (/home/kenan/code/pacote/node_modules/npm-pick-manifest/index.js:35:11) 
    at fetchPackument.then.packument (/home/kenan/code/pacote/lib/fetchers/registry/manifest.js:39:14)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
```

Before that patch, it would log the registry's manifest for `pacote`, but with the `_resolved` field set to the custom tarball URL.

Tested with Node.js 9.4.0 on Linux 4.14.13.

---

I discovered this whilst playing around with `npmc`. I noticed that a `package.json` like:

```json
{
  "dependencies": {
    "pacote": "https://github.com/zkat/pacote/archive/v7.1.1.tar.gz"
  }
}
```

had begun throwing the above error. I `git bisect`ed and found that https://github.com/npm/npm/commit/dd072347fdbbe7632cace28190f72868a4790f81 was the cause, so I then came to this repo and did another `git bisect` here to find the offending commit.

**Comment by zkat** [comment] 2018-03-15 07:56
This seems to have been fixed between `7.1.1` and now (which makes sense, since a lot of stuff was fixed precisely with the `opts.resolved` code I added. I'm gonna close this, since I can't reproduce it (and I can definitely repro it if I switch to 7.1.1). Cheers! And thanks for keeping a keen eye out for this stuff. 🎉

**Closed as completed by zkat** 2018-03-15 07:56 UTC
Labels: bug
